import type { Metadata } from "next";
import { Roboto, Bebas_Neue } from "next/font/google";
import "../styles/globals.css";

const bebas_neue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Taras Bilyk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto} ${bebas_neue}` }>{children}</body>
    </html>
  );
}
