import type { Metadata } from "next";
import { Roboto, Roboto_Mono, Bebas_Neue } from "next/font/google";
import "../styles/globals.css";

const bebas_neue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
});

const roboto_mono = Roboto_Mono({
  weight: "400",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bilyk Taras",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto}${roboto_mono} ${bebas_neue}`}>
        {children}
      </body>
    </html>
  );
}
